<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <UserSecretsId>5724ae88-4f48-4d89-ba2f-7dcb0b1f7d1e</UserSecretsId>
    <Company>Calypso Systems, LLC</Company>
    <Authors>Joe Schmitt</Authors>
    <Description>MatrixEase Data Manga and Visualization</Description>
    <AssemblyName>MatrixEase.Web</AssemblyName>
    <RootNamespace>MatrixEase.Web</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MatrixEase.Manga\MatrixEase.Manga.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>MatrixEase.Web.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

</Project>
